set -g prefix C-g
set -g mouse on
set -g pane-border-style 'fg=default'
set -g pane-active-border-style 'fg=default'
set -g status-style bg=default
set -g status-position top
set -g default-terminal ",xterm-256color:Tc"
set-window-option -g xterm-keys on
