set -g prefix C-g
set -g mouse on
set -g pane-border-style 'fg=default'
set -g pane-active-border-style 'fg=default'
set-option -g status-style bg=default
set-option -g status-position top
set-option -ga terminal-overrides ",xterm-256color:Tc"
